### ISSUE TITLE
Not campable for latest magisk version

### ISSUE THREAD

**Issue by KinG-InFeT** [Magisk-Modules-Repo/liboemcryptodisabler#6]
Out error after install mobule
Unzip error

**Comment by mingkee27** [comment]
What is your version?
I had it added (1.5) through Fox's MMM and it works OK

**Comment by KinG-InFeT** [comment]
yes, with Fox's MMM works, without Fox's MMM not work can you write correct guide into readme? it would be useful

**Comment by mingkee27** [comment]
It's simple
You can download a copy and add it as module in Magisk
However, this method doesn't work with OnePlus due to liboemcrypo.so is in different location (/odm/lib/)
If you have OnePlus 10 pro or 10T, check it out
https://forum.xda-developers.com/t/root-10t-5g.4484233/page-10#post-88148645

**Comment by KinG-InFeT** [comment]
yes, thank you
